"use client";

import { Button } from "@/components/ui/button";
import { useState } from "react";

export type PdfSection = {
  label: string;
  rows: [string, string][];
};

type Props = {
  sections: PdfSection[];
  imgSrc?: string;
  fileName?: string;
  title?: string;
  disabled?: boolean;
};

export function ExportPdfButton({
  sections,
  imgSrc,
  fileName = "metadata.pdf",
  title = "Metadata Report",
  disabled,
}: Props) {
  const [loading, setLoading] = useState(false);

  const handleExport = async () => {
    setLoading(true);
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ unit: "pt", format: "a4" });
      const pageW = doc.internal.pageSize.getWidth();
      const margin = 40;
      let y = 50;

      // Title
      doc.setFontSize(20);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0, 0, 0);
      doc.text(title, margin, y);
      y += 10;

      // Divider line
      doc.setDrawColor(200, 200, 200);
      doc.line(margin, y, pageW - margin, y);
      y += 20;

      // Embed image
      if (imgSrc) {
        try {
          const imgW = 180;
          const imgH = 135;
          doc.addImage(imgSrc, "JPEG", margin, y, imgW, imgH);
          y += imgH + 20;
        } catch {}
      }

      // Sections
      for (const sec of sections) {
        if (y > 740) { doc.addPage(); y = 50; }

        // Section header
        doc.setFontSize(10);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(180, 100, 0);
        doc.text(sec.label.toUpperCase(), margin, y);
        y += 4;
        doc.setDrawColor(180, 100, 0);
        doc.setLineWidth(0.5);
        doc.line(margin, y, pageW - margin, y);
        y += 12;

        // Rows
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(9);
        for (const [k, v] of sec.rows) {
          if (y > 780) { doc.addPage(); y = 50; }
          const labelX = margin;
          const valueX = margin + 160;
          doc.setFont("helvetica", "bold");
          doc.text(k, labelX, y);
          doc.setFont("helvetica", "normal");
          const lines = doc.splitTextToSize(String(v), pageW - valueX - margin);
          doc.text(lines, valueX, y);
          y += Math.max(14, lines.length * 12);
        }
        y += 10;
      }

      // Footer
      const pageCount = doc.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(
          `Generated by Dev Toolbox · Page ${i} of ${pageCount}`,
          margin,
          doc.internal.pageSize.getHeight() - 20
        );
      }

      doc.save(fileName);
    } catch (e) {
      console.error("PDF export failed:", e);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Button
      variant="outline"
      onClick={handleExport}
      disabled={disabled || loading}
      className="w-full"
    >
      {loading ? "Generating PDF..." : "↓ Download as PDF"}
    </Button>
  );
}
