export type Tool = {
  name: string;
  category: "developer" | "text" | "utility" | "image";
  description: string;
  icon: string;
  href: string;
  isPremium: boolean;
};

export const TOOLS: Tool[] = [
  // ── Free tools ────────────────────────────────────────────────
  {
    name: "JSON Formatter",
    category: "developer",
    description: "Format and validate JSON with syntax highlighting",
    icon: "{ }",
    href: "/dashboard/json-to-yaml",
    isPremium: false,
  },
  {
    name: "Base64 Encoder/Decoder",
    category: "developer",
    description: "Encode and decode Base64 strings",
    icon: "→",
    href: "/dashboard/base64-encoder",
    isPremium: false,
  },
  {
    name: "UUID Generator",
    category: "developer",
    description: "Generate random UUIDs v4",
    icon: "✓",
    href: "/dashboard/uuid-generator",
    isPremium: false,
  },
  {
    name: "URL Encoder/Decoder",
    category: "developer",
    description: "Encode and decode URLs",
    icon: "∞",
    href: "/dashboard/url-encoder",
    isPremium: false,
  },
  // ── Premium tools ─────────────────────────────────────────────
  {
    name: "JWT Decoder",
    category: "developer",
    description: "Decode and analyze JWT tokens",
    icon: "🔑",
    href: "/dashboard/jwt-decoder",
    isPremium: true,
  },
  {
    name: "Hash Generator",
    category: "developer",
    description: "Generate MD5, SHA1, SHA256, and SHA512 hashes",
    icon: "#",
    href: "/dashboard/hash-generator",
    isPremium: true,
  },
  {
    name: "SQL Formatter",
    category: "developer",
    description: "Format and beautify SQL queries",
    icon: "📝",
    href: "/dashboard/sql-formatter",
    isPremium: true,
  },
  {
    name: "Word Counter",
    category: "text",
    description: "Count words, characters, and lines",
    icon: "#",
    href: "/dashboard/word-counter",
    isPremium: false,
  },
  {
    name: "Text Case Converter",
    category: "text",
    description: "Convert between uppercase, lowercase, and title case",
    icon: "A",
    href: "/dashboard/case-converter",
    isPremium: false,
  },
  {
    name: "Regex Tester",
    category: "text",
    description: "Test and debug regular expressions",
    icon: ".*",
    href: "/dashboard/regex-tester",
    isPremium: true,
  },
  {
    name: "Markdown Previewer",
    category: "text",
    description: "Preview Markdown in real-time",
    icon: "#",
    href: "/dashboard/markdown-preview",
    isPremium: true,
  },
  {
    name: "Text Diff",
    category: "text",
    description: "Compare two texts and highlight differences",
    icon: "~",
    href: "/dashboard/text-diff",
    isPremium: true,
  },
  {
    name: "Remove Duplicate Lines",
    category: "text",
    description: "Remove duplicate lines from your text",
    icon: "⚔️",
    href: "/dashboard/remove-duplicate-lines",
    isPremium: true,
  },
  {
    name: "Color Converter",
    category: "utility",
    description: "Convert between HEX, RGB, and HSL colors",
    icon: "◯",
    href: "/dashboard/color-converter",
    isPremium: false,
  },
  {
    name: "QR Code Generator",
    category: "utility",
    description: "Generate QR codes from text and URLs",
    icon: "▦",
    href: "/dashboard/qr-code-generator",
    isPremium: true,
  },
  {
    name: "Unix Timestamp",
    category: "utility",
    description: "Convert between Unix timestamps and human-readable dates",
    icon: "⏱",
    href: "/dashboard/unix-timestamp",
    isPremium: false,
  },
  {
    name: "Password Generator",
    category: "utility",
    description: "Generate secure random passwords with custom options",
    icon: "🔐",
    href: "/dashboard/password-generator",
    isPremium: true,
  },

  // ── Newly requested tools ────────────────────────────────────
  {
    name: "JSON CSV Converter",
    category: "developer",
    description: "Convert JSON to CSV and CSV to JSON instantly",
    icon: "⇄",
    href: "/dashboard/tools/json-csv-converter",
    isPremium: false,
  },
  {
    name: "Cron Expression Builder",
    category: "developer",
    description:
      "Build cron expressions and parse them into human-readable text",
    icon: "⏰",
    href: "/dashboard/tools/cron-expression-builder",
    isPremium: true,
  },
  {
    name: "URL Parser Inspector",
    category: "developer",
    description: "Inspect URL components and query parameters",
    icon: "🔍",
    href: "/dashboard/tools/url-parser-inspector",
    isPremium: false,
  },
  {
    name: "JWT Generator",
    category: "developer",
    description: "Generate JWT tokens with custom payload and claims",
    icon: "🔏",
    href: "/dashboard/tools/jwt-generator",
    isPremium: true,
  },
  {
    name: "Base64 File Encoder Decoder",
    category: "developer",
    description: "Encode files to Base64 and decode Base64 back to files",
    icon: "📎",
    href: "/dashboard/tools/base64-file-encoder-decoder",
    isPremium: true,
  },
  {
    name: "Diff Patch Generator",
    category: "developer",
    description: "Generate unified diffs and patch text",
    icon: "🩹",
    href: "/dashboard/tools/diff-patch-generator",
    isPremium: true,
  },
  {
    name: "HTML Markdown Converter",
    category: "text",
    description: "Convert HTML to Markdown and Markdown to HTML",
    icon: "🧾",
    href: "/dashboard/tools/html-markdown-converter",
    isPremium: false,
  },
  {
    name: "Lorem Ipsum Fake Data",
    category: "text",
    description: "Generate lorem ipsum text and fake data samples",
    icon: "✍️",
    href: "/dashboard/tools/lorem-ipsum-fake-data",
    isPremium: false,
  },
  {
    name: "UUID Bulk Generator",
    category: "utility",
    description: "Generate UUIDs in bulk with copy/download support",
    icon: "🧬",
    href: "/dashboard/tools/uuid-bulk-generator",
    isPremium: false,
  },
  {
    name: "Timezone Meeting Planner",
    category: "utility",
    description: "Compare timezones and find the best meeting overlap",
    icon: "🌍",
    href: "/dashboard/tools/timezone-meeting-planner",
    isPremium: true,
  },
  {
    name: "HTTP Status Lookup",
    category: "developer",
    description: "Search and explain HTTP status codes quickly",
    icon: "📚",
    href: "/dashboard/tools/http-status-lookup",
    isPremium: false,
  },
  {
    name: "SQL Prettify Minify",
    category: "developer",
    description: "Prettify or minify SQL queries with one click",
    icon: "🗃️",
    href: "/dashboard/tools/sql-prettify-minify",
    isPremium: true,
  },
  {
    name: "Regex Cheatsheet Templates",
    category: "text",
    description: "Quick regex templates and pattern cheat-sheet",
    icon: "📐",
    href: "/dashboard/tools/regex-cheatsheet-templates",
    isPremium: false,
  },
  {
    name: "Password Strength Auditor",
    category: "utility",
    description: "Estimate entropy and crack-time for passwords",
    icon: "🛡️",
    href: "/dashboard/tools/password-strength-auditor",
    isPremium: true,
  },

  // ── Image tools (new section) ────────────────────────────────
  {
    name: "Image Resizer",
    category: "image",
    description: "Resize images by width, height, or percentage",
    icon: "🖼️",
    href: "/dashboard/tools/image-resizer",
    isPremium: false,
  },
  {
    name: "Image Compressor",
    category: "image",
    description: "Compress images while preserving visual quality",
    icon: "🗜️",
    href: "/dashboard/tools/image-compressor",
    isPremium: false,
  },
  {
    name: "Image Cropper",
    category: "image",
    description: "Crop images to custom dimensions and aspect ratios",
    icon: "✂️",
    href: "/dashboard/tools/image-cropper",
    isPremium: true,
  },
  {
    name: "Image Format Converter",
    category: "image",
    description: "Convert between PNG, JPG, WEBP, and more",
    icon: "🔄",
    href: "/dashboard/tools/image-format-converter",
    isPremium: false,
  },
  {
    name: "Background Remover",
    category: "image",
    description: "Remove image backgrounds for cleaner assets",
    icon: "🧽",
    href: "/dashboard/tools/background-remover",
    isPremium: true,
  },
  {
    name: "Image Watermark",
    category: "image",
    description: "Add text or logo watermarks to images",
    icon: "💧",
    href: "/dashboard/tools/image-watermark",
    isPremium: true,
  },
  {
    name: "Image to Base64",
    category: "image",
    description: "Convert image files into Base64 strings",
    icon: "🧾",
    href: "/dashboard/tools/image-to-base64",
    isPremium: false,
  },
  {
    name: "Base64 to Image",
    category: "image",
    description: "Decode Base64 strings into downloadable images",
    icon: "📷",
    href: "/dashboard/tools/base64-to-image",
    isPremium: false,
  },
  {
    name: "Color Palette Extractor",
    category: "image",
    description: "Extract dominant and accent colors from images",
    icon: "🎨",
    href: "/dashboard/tools/color-palette-extractor",
    isPremium: false,
  },
  {
    name: "EXIF Metadata Viewer",
    category: "image",
    description: "Read camera and EXIF metadata from photos",
    icon: "🧷",
    href: "/dashboard/tools/exif-metadata-viewer",
    isPremium: false,
  },
  {
    name: "Screenshot Annotator",
    category: "image",
    description: "Annotate screenshots with arrows, shapes, and text",
    icon: "📝",
    href: "/dashboard/tools/screenshot-annotator",
    isPremium: true,
  },
  {
    name: "Batch Image Renamer",
    category: "image",
    description: "Rename multiple image files using smart patterns",
    icon: "📦",
    href: "/dashboard/tools/batch-image-renamer",
    isPremium: true,
  },
];

export const TOOL_CATEGORIES = [
  "developer",
  "text",
  "utility",
  "image",
] as const;

